apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-flower-client-fe
  namespace: buy-flower-staging
  labels:
    app: buy-flower-client-fe
spec:
  replicas: 1
  template:
    metadata:
      name: buy-flower-client-fe
      labels:
        app: buy-flower-client-fe
    spec:
      nodeSelector:
        ram: high
      containers:
        - name: buy-flower-client-fe
          image: ghcr.io/whoant221/buy-flower-fe:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
      restartPolicy: Always
  selector:
    matchLabels:
      app: buy-flower-client-fe