apiVersion: v1
kind: Service
metadata:
  name: buy-flower-client-fe
  namespace: buy-flower-staging
spec:
  selector:
    app: buy-flower-client-fe
  ports:
    - port: 81
      targetPort: 80
      nodePort: 30004
  type: NodePort