apiVersion: v1
kind: Service
metadata:
  name: fe-buy-flower-client
  namespace: buy-flower-staging
spec:
  selector:
    app: fe-buy-flower-client
  ports:
    - port: 81
      targetPort: 80
      nodePort: 30004
  type: NodePort